sylius_grid:
    grids:
        toro_admin_badge_item:
            driver:
                name: doctrine/orm
                options:
                    class: %toro.model.badge_item.class%
                    repository:
                        method: createLocaledQueryBuilder
                        arguments: ["%locale%"]
            sorting:
                code: desc

            fields:
                code:
                    type: string
                    label: Code
                    sortable: ~
                name:
                    type: string
                    label: Name
                    sortable: translation.name
                class:
                    type: string
                    label: Class
                type:
                    type: string
                    label: Type
                createdAt:
                    type: datetime
                    label: Create at
                    sortable: ~
                    options:
                        format: d-m-Y H:i

            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
